In [1]:
import pandas as pd
import numpy as np
import os

In [5]:
download_dataset()

Introduce la url: https://www.kaggle.com/shivamb/netflix-shows

0

In [7]:
data = pd.read_csv("data/dataset.csv", encoding = "ISO-8859-1")
display(data.sample(3))

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6036,s6037,TV Show,Th Eena Meena Deeka Chase Comedy Show,Dheeraj Berry,"Sanjay Keni, Priya Raina",India,"March 31, 2018",2015,TV-Y7,1 Season,"Kids' TV, TV Comedies","A hungry fox and three resourceful, surprising..."
2852,s2853,Movie,How to Win the US Presidency,Cal Saville,NaN,United States,"August 1, 2016",2016,TV-PG,51 min,Documentaries,This whimsical look at rough-and-tumble Americ...
7119,s7120,Movie,"To Wong Foo, Thanks for Everything! Julie Newmar",Beeban Kidron,"Patrick Swayze, Wesley Snipes, John Leguizamo,...",United States,"August 1, 2019",1995,PG-13,108 min,"Comedies, Cult Movies, LGBTQ Movies",Three New York drag queens on their way to Hol...

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

In [7]:
data.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [8]:
data['date_added'] = data['date_added'].fillna('NaN Data')
data['year'] = data['date_added'].apply(lambda x: x[-4: len(x)])
data['month'] = data['date_added'].apply(lambda x: x.split(' ')[0])

display(data.head())

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
0,s1,TV Show,3%,NaN,"JoÃ£o Miguel, Bianca Comparato, Michel Gomes, ...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020,August
1,s2,Movie,7:19,Jorge Michel Grau,"DemiÃ¡n Bichir, HÃ©ctor Bonilla, Oscar Serrano...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016,December
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018,December
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017,November
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020,January

In [9]:
data.to_csv("netflix_clean.csv")